import clpFfiJsModuleInit from "clp-ffi-js/node";
import {readFile, writeFile} from "fs/promises"
import {resolve} from "path"

async function loadTrace (path) {
    const trace = await readFile(resolve(path));
    const Module = await clpFfiJsModuleInit();
    const decoder = new Module.ClpStreamReader(trace, {
        timestampKey: {isAutoGenerated: true, parts: ["timestamp", "unix_millisecs"]},
        logLevelKey: {isAutoGenerated: true, parts: ["level", "name"]}}
    );
    const logs = decoder.decodeRange(0, decoder.deserializeStream(), false);
    return logs;
}


const collectInputs = async (path) => {
    const logs = await loadTrace(path);
    const inputs = [];

    for (const log of logs) {
        const msg = JSON.parse(log.message);
        if (msg && "user-generated" in msg) {
            const userGenerated = msg["user-generated"];
            if (userGenerated.type === "argument") {
                inputs.push(userGenerated);
            }
        } else {
            throw new Error(`Log message does not contain "user-generated" field: ${log.message}`); 
        }
    }
    return inputs;
}

const pathToTrace = "./traces/511f5ab8-53c6-46e4-9579-493dcd2ab78e.clp.zst";
const inputs = await collectInputs(pathToTrace);
console.log(inputs);

export default collectInputs;